name: FlameCard
description: Card Game made using Flutter and Flame
version: 1.0.0
publish_to: none


environment:
  sdk: ^3.0.0
  flutter: ^3.13.0
    
flutter:
  assets:
    - assets/images/
    - assets/audio/


dependencies:
  flutter:
    sdk: flutter
  flame: ^1.20.0
  path_provider: ^2.1.4
  audioplayers: ^6.1.0
  # path_provider: ^2.1.4
  flame_audio: ^2.10.5
